#!/usr/bin/env python3
"""Topic-specific lesson outlines for donor DevOps & cloud courses."""

from __future__ import annotations

MODULES: dict[str, dict] = {
    'devops/01-devops-mindset': {
        'goals': ['Define DevOps as a delivery system (not a job title or a tool list)', 'Sketch a value stream from commit to production for a small API', 'Name lead time, deploy frequency, change failure rate, and MTTR in plain words'],
        'why': 'Teams that only add tools without fixing handoffs still ship slowly. A clear value stream shows where time and risk actually hide.',
        'ideas': ['**Flow over heroics** — frequent small changes beat rare big releases.', '**You build it, you run it (shared)** — developers and ops share outcomes, not blame.', '**Feedback loops** — telemetry and incidents must reach the people who can change the code.', '**Constraints first** — map the bottleneck before buying another platform.'],
        'example': '### Lab: map a value stream (45 minutes)\n\nPick a real or sample web API. Draw four boxes: **Commit → Build → Deploy → Observe**.\n\nFor each box write: owner, typical wait time, and one failure mode.\n\nThen answer:\n1. Where does work sit idle the longest?\n2. Which step needs a human every time?\n3. What is the smallest automation that would cut wait time this week?\n\n```text\nExample (fill yours in):\nCommit  → PR review (owner: team, wait: 1d, fail: flaky tests)\nBuild   → CI (owner: platform, wait: 12m, fail: secret missing)\nDeploy  → manual SSH (owner: ops, wait: 2h, fail: wrong host)\nObserve → none (owner: ?, wait: ?, fail: users report first)\n```\n',
        'practice': ['Write a one-page value-stream note for your sample service.', 'List the four DORA-style metrics and invent honest baseline guesses.', 'Propose one change that improves *flow*, not just tooling.'],
        'mistakes': ['Renaming the ops team “DevOps” without changing the release process', 'Buying a CI product before fixing branch and review habits', 'Optimising a step that is not the bottleneck'],
        'stretch': 'Interview one teammate (or invent a persona) and update the stream with their wait times.',
        'quiz': [
            ('DevOps is best described as…', ['A single vendor product', 'A delivery system of culture, process, and automation', 'Only writing Dockerfiles', 'Avoiding production ownership'], 1),
            ('Which metric pair helps you see both speed and safety?', ['Font size and colour contrast', 'Deploy frequency and change failure rate', 'CPU brand and laptop RAM', 'Number of Slack channels'], 1),
            ('What should you map before buying a new platform?', ['The value stream and bottleneck', 'Every trademark in the brochure', 'Your favourite colour theme', 'How to disable logging'], 0),
            ('A healthy feedback loop means…', ['Incidents never reach developers', 'Telemetry and failures reach people who can change the system', 'Only managers see dashboards', 'Users must email screenshots forever'], 1),
            ('Why prefer small frequent changes?', ['They are harder to review', 'They shrink blast radius and speed learning', 'They remove the need for tests', 'They hide failures forever'], 1),
        ],
    },
    'devops/02-git-branching-for-teams': {
        'goals': ['Choose a simple trunk-based or short-lived branch workflow', 'Write a PR description that helps reviewers and future you', 'Use protected branches and required checks without drama'],
        'why': 'Most delivery pain starts in Git habits: long-lived branches, unclear ownership, and merges that nobody can reverse.',
        'ideas': ['**Short-lived branches** — merge within a day or two when you can.', '**Main stays releasable** — broken main blocks everyone.', '**PR as a design note** — why, what, how to test, how to roll back.', '**Protect main** — require reviews + CI; avoid force-push on shared branches.'],
        'example': '### Lab: branch, commit, open a PR shape\n\n```bash\ngit switch -c feat/health-endpoint\n# …edit…\ngit add -A\ngit commit -m "feat: add /health for load balancer checks"\ngit push -u origin HEAD\n```\n\nDraft a PR body with these headings:\n\n```markdown\n## Why\n## What changed\n## How to test\n## Rollback\n```\n',
        'practice': ['Create a short-lived branch and a PR template note in your lab repo.', 'List which checks should be required on `main`.', 'Practise a revert plan: `git revert` vs redeploy previous artefact.'],
        'mistakes': ['Week-long feature branches with no sync from main', 'Committing secrets or huge binaries', 'Force-pushing shared branches'],
        'stretch': 'Add a CODEOWNERS file for one critical path.',
        'quiz': [
            ('Why keep branches short-lived?', ['To maximise merge conflicts', 'To reduce drift and make reviews smaller', 'So CI never runs', 'To avoid writing commit messages'], 1),
            ('What belongs in a good PR description?', ['Only “fix”', 'Why, what, how to test, rollback', 'Your password', 'A meme and nothing else'], 1),
            ('Protected `main` usually means…', ['Anyone can force-push', 'Required checks and reviews before merge', 'No CI allowed', 'Secrets must live in the repo'], 1),
            ('If a bad commit reaches main, a safe first option is often…', ['Delete the remote repository', 'Revert or redeploy a known-good artefact', 'Disable all tests forever', 'Ignore production errors'], 1),
            ('Trunk-based development encourages…', ['Months of isolated work', 'Frequent integration to main with feature flags if needed', 'Never opening PRs', 'Editing production by hand only'], 1),
        ],
    },
    'devops/03-ci-pipelines': {
        'goals': ['Explain what CI must prove on every push', 'Sketch a pipeline: lint → test → build artefact', 'Separate flaky tests from real failures'],
        'why': 'CI is the team’s shared safety net. If it is slow or flaky, people bypass it — and production pays.',
        'ideas': ['**Fast feedback** — fail in minutes, not hours.', '**Deterministic builds** — lock dependencies; avoid “works on my machine”.', '**Artefacts** — build once; promote the same binary/image.', '**Secrets in the runner** — never in the repo.'],
        'example': '### Lab: minimal GitHub Actions shape\n\n```yaml\nname: ci\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: "20" }\n      - run: npm ci\n      - run: npm test\n      - run: npm run build\n```\n\nExtend later with lint, caching, and uploading a build artefact.\n',
        'practice': ['Add a CI workflow that runs tests on every PR.', 'Time a green run; write a goal to keep it under a threshold you choose.', 'Document where secrets live (CI settings), not in markdown.'],
        'mistakes': ['Only testing on developer laptops', 'Rebuilding differently for staging vs production', 'Ignoring flaky tests until nobody trusts CI'],
        'stretch': 'Cache dependencies and measure the time saved.',
        'quiz': [
            ('CI should primarily…', ['Deploy to production on every keystroke', 'Prove each change builds and passes automated checks', 'Replace code review entirely', 'Store production passwords in git'], 1),
            ('“Build once, promote many” means…', ['Rebuild with different flags per environment casually', 'Create one artefact and promote the same artefact', 'Never build artefacts', 'Only build on Fridays'], 1),
            ('Where should CI secrets live?', ['Committed as plain text', 'In the CI secret store / environment', 'In public screenshots', 'In the README title'], 1),
            ('A flaky test that fails randomly should be…', ['Ignored forever with no ticket', 'Quarantined/fixed so CI stays trustworthy', 'Used as the only gate to production', 'Deleted along with all tests'], 1),
            ('Fast CI feedback helps because…', ['People are less likely to bypass checks', 'It removes the need for any tests', 'It guarantees zero bugs', 'It replaces monitoring'], 0),
        ],
    },
    'devops/04-cd-and-releases': {
        'goals': ['Distinguish continuous delivery from continuous deployment', 'Describe blue/green or canary at a high level', 'Write a release checklist with rollback'],
        'why': 'Shipping is a product skill. Unplanned releases create outages; planned, reversible releases build trust.',
        'ideas': ['**Delivery vs deployment** — CD often means *always releasable*; auto-prod is optional.', '**Same artefact** — staging and prod differ by config, not by mystery rebuilds.', '**Progressive delivery** — canary/blue-green limit blast radius.', '**Rollback is a feature** — practise it before you need it.'],
        'example': '### Lab: release runbook (one page)\n\n```markdown\n# Release: api v1.4.2\n## Pre\n- [ ] CI green on tag\n- [ ] Migrations backward compatible?\n- [ ] Feature flag default?\n## Deploy\n- [ ] Deploy to staging; smoke /health and one critical path\n- [ ] Deploy to prod (canary 5% → 25% → 100%)\n## Verify\n- [ ] Error rate, latency, one business metric\n## Rollback\n- [ ] Redeploy previous artefact / flip flag off\n- [ ] Who to notify\n```\n',
        'practice': ['Write a release checklist for your sample API.', 'Decide: continuous delivery (manual prod click) vs continuous deployment.', 'Document one rollback method you could execute in under 15 minutes.'],
        'mistakes': ['Hotfixing production without a recorded change', 'Forward-only migrations with no expand/contract plan', 'No smoke tests after deploy'],
        'stretch': 'Add a feature flag for a risky change and practise toggling it.',
        'quiz': [
            ('Continuous delivery usually means…', ['Main is always in a releasable state', 'You never write tests', 'Production has no monitoring', 'Every laptop is a prod server'], 0),
            ('A canary release is useful because…', ['It ships to 100% of users instantly always', 'It limits blast radius while you watch metrics', 'It removes the need for CI', 'It hides all errors'], 1),
            ('Staging and production should preferably run…', ['Different mystery builds each time', 'The same artefact with different configuration', 'No version numbers', 'Only local Docker without tags'], 1),
            ('A release checklist should include…', ['Rollback and verification steps', 'Only a celebration emoji', 'Disabling logs', 'Deleting backups'], 0),
            ('Practising rollback matters because…', ['You will never need it', 'Stress is a bad time to invent the procedure', 'Rollback is illegal', 'Monitoring replaces rollback'], 1),
        ],
    },
    'devops/05-containers-basics': {
        'goals': ['Explain image vs container', 'Write a simple Dockerfile for a web app', 'Tag images and avoid `latest` in production notes'],
        'why': 'Containers package runtime + app so CI and prod share the same shape. Mis-tagged images cause “it worked yesterday” incidents.',
        'ideas': ['**Image = recipe snapshot; container = running instance.**', '**One process focus** — keep containers simple; compose for multi-service.', '**Pin base images** — digest or specific tags for reproducibility.', '**Non-root when you can** — smaller privilege surface.'],
        'example': '### Lab: Dockerfile for a tiny Node API\n\n```dockerfile\nFROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY . .\nUSER node\nEXPOSE 3000\nCMD ["node", "server.js"]\n```\n\n```bash\ndocker build -t myapi:0.1.0 .\ndocker run --rm -p 3000:3000 myapi:0.1.0\ncurl -s localhost:3000/health\n```\n',
        'practice': ['Containerise your sample app and hit a health endpoint.', 'Record the image tag you used (not only `latest`).', 'List what must stay *out* of the image (secrets, local `.env`).'],
        'mistakes': ['Baking secrets into layers', 'Huge images with unused toolchains', 'Running everything as root “just because”'],
        'stretch': 'Multi-stage build to keep the final image slim.',
        'quiz': [
            ('An image is best thought of as…', ['A running process only', 'An immutable filesystem snapshot + metadata', 'A VPN tunnel', 'A git branch'], 1),
            ('Why avoid relying on `:latest` in production?', ['It is always slower', 'It is ambiguous and can change underneath you', 'Docker forbids it', 'It disables networking'], 1),
            ('Secrets should be…', ['COPY’d into the Dockerfile permanently', 'Injected at runtime via env/secret stores', 'Printed in build logs on purpose', 'Committed next to the Dockerfile'], 1),
            ('Pinning a base image helps…', ['Reproducible builds', 'Random breakage as a feature', 'Skipping tests', 'Hiding CVEs forever'], 0),
            ('`docker run` starts…', ['A container from an image', 'A new cloud region', 'A Terraform backend', 'A DNS zone'], 0),
        ],
    },
    'devops/06-compose-and-local-envs': {
        'goals': ['Run app + dependency (e.g. DB) with Compose', 'Use env files without committing secrets', 'Match local topology loosely to staging'],
        'why': 'Local parity reduces “works on my machine”. Compose is the fastest way to learn multi-service wiring before Kubernetes.',
        'ideas': ['**Declare services** — app, db, cache as code.', '**Networks & volumes** — data that must survive restarts.', '**.env for local only** — never commit real credentials.', '**Healthchecks** — start order that waits for readiness.'],
        'example': '### Lab: app + Postgres sketch\n\n```yaml\nservices:\n  api:\n    build: .\n    ports: ["3000:3000"]\n    environment:\n      DATABASE_URL: postgres://app:app@db:5432/app\n    depends_on:\n      db:\n        condition: service_healthy\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_PASSWORD: app\n      POSTGRES_USER: app\n      POSTGRES_DB: app\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U app"]\n      interval: 5s\n      retries: 5\n```\n\n```bash\ndocker compose up --build\n```\n',
        'practice': ['Add Compose for app + one dependency.', 'Document how a new teammate starts the stack in under five commands.', 'Ensure `.env` is gitignored; provide `.env.example` with fake values.'],
        'mistakes': ['Committing real passwords in compose files', 'Assuming Compose equals production Kubernetes', 'No healthcheck so the API starts before the DB'],
        'stretch': 'Add a `mailhog` or similar stub service for local email.',
        'quiz': [
            ('Docker Compose is mainly for…', ['Declaring multi-container local/dev topologies', 'Replacing all cloud networking forever', 'Storing production secrets in git', 'Compiling Java only'], 0),
            ('`.env.example` should contain…', ['Production passwords', 'Placeholder keys showing required variables', 'Private SSH keys', 'Nothing useful'], 1),
            ('A DB healthcheck helps because…', ['The API can wait until Postgres is ready', 'It deletes volumes nightly', 'It disables networking', 'It replaces backups'], 0),
            ('Volumes are useful when…', ['You need data to survive container restarts', 'You want to lose all data every boot always', 'You hate persistence', 'You only run one-shot scripts'], 0),
            ('Local Compose parity should be…', ['Identical to every production detail always', 'Close enough to catch wiring issues early', 'Avoided completely', 'Done only on paper'], 1),
        ],
    },
    'devops/07-observability-basics': {
        'goals': ['Separate logs, metrics, and traces', 'Add structured logs and a basic RED/USE style check', 'Define one SLO-ish symptom for your service'],
        'why': 'You cannot improve what you cannot see. Guessing during incidents wastes customers’ time.',
        'ideas': ['**Logs** — events; prefer structured JSON.', '**Metrics** — aggregates for dashboards/alerts.', '**Traces** — request path across services.', '**Alert on symptoms** — user pain, not every CPU blip.'],
        'example': '### Lab: structured log + simple metric\n\n```js\n// example: log one request\nconsole.log(JSON.stringify({\n  level: "info",\n  msg: "request",\n  route: "/checkout",\n  status: 200,\n  latency_ms: 42,\n  request_id: "abc123"\n}));\n```\n\nPick one alert idea: “5xx rate > 2% for 5 minutes” or “p95 latency > 800ms”.\n',
        'practice': ['Add `request_id` to logs for one endpoint.', 'List three signals you would graph for your API.', 'Write one alert in plain language tied to user impact.'],
        'mistakes': ['Logging secrets or full card numbers', 'Alert fatigue from noisy low-value pages', 'No correlation IDs across services'],
        'stretch': 'Sketch a tiny dashboard: traffic, errors, latency.',
        'quiz': [
            ('Metrics are best for…', ['Aggregated trends and alerting', 'Storing raw PII forever', 'Replacing all logs', 'Hiding outages'], 0),
            ('Structured logs help because…', ['Machines can query fields reliably', 'They are always shorter than text', 'They remove the need for metrics', 'They encrypt themselves'], 0),
            ('A good alert usually tracks…', ['A symptom users feel (errors/latency)', 'Every debug log line', 'Laptop battery percent', 'Number of README adjectives'], 0),
            ('Traces help you…', ['See a request across services', 'Delete Kubernetes', 'Avoid IAM', 'Skip backups'], 0),
            ('Why include a request id?', ['To correlate logs for one user journey', 'To replace authentication', 'To slow the server down', 'To satisfy a random style guide only'], 0),
        ],
    },
    'devops/08-incident-response': {
        'goals': ['Follow a simple incident timeline: detect → mitigate → resolve → learn', 'Communicate status without blame', 'Write a short blameless postmortem outline'],
        'why': 'Incidents are inevitable. Mature teams minimise impact and learn; immature teams panic and hide.',
        'ideas': ['**Mitigate first** — stop the bleeding before root-causing forever.', '**Single incident lead** — clear roles beat chaos.', '**Status updates** — what we know, what we’re doing, next update time.', '**Blameless learning** — fix systems, not people.'],
        'example': '### Lab: tabletop incident (30 minutes)\n\nScenario: checkout returns 500s after a deploy.\n\n1. Who is incident lead?\n2. First mitigate action (rollback vs flag)?\n3. What do you tell support/status page in one paragraph?\n4. What evidence do you capture (deploy id, graphs, recent changes)?\n\nPostmortem outline:\n\n```markdown\n## Summary\n## Impact\n## Timeline\n## Root causes (systems)\n## Action items (owner + date)\n```\n',
        'practice': ['Run the tabletop with a friend or aloud to yourself.', 'Draft a status update template.', 'List three action items that would prevent a repeat.'],
        'mistakes': ['Debating root cause while customers are still down', 'Blaming individuals in the write-up', 'No follow-up actions with owners'],
        'stretch': 'Add a “break glass” access note: who can roll back prod.',
        'quiz': [
            ('During an active outage, prioritise…', ['Mitigation and clear communication', 'Writing a perfect novel', 'Disabling monitoring', 'Deleting logs'], 0),
            ('A blameless postmortem focuses on…', ['Punishing the on-call', 'Systemic fixes and learning', 'Hiding the timeline', 'Skipping action items'], 1),
            ('Status updates should include…', ['What we know, what we’re doing, next update time', 'Internal arguments verbatim', 'User passwords', 'Nothing until fully fixed'], 0),
            ('Why assign an incident lead?', ['To reduce conflicting decisions', 'To remove engineers from the call', 'To avoid documentation', 'To slow mitigation'], 0),
            ('Action items should have…', ['Owners and dates', 'No owners', 'Only vibes', 'Secret Slack channels with no notes'], 0),
        ],
    },
    'devops/09-security-in-the-pipeline': {
        'goals': ['List SAST/dependency/scan checkpoints in CI', 'Explain least privilege for deploy credentials', 'Handle secrets with rotation in mind'],
        'why': 'Security bolted on at the end fails. Shifting checks left catches issues when fixes are cheap.',
        'ideas': ['**Dependency scanning** — know what you ship.', '**Least privilege CI roles** — deploy credentials are crown jewels.', '**Signed/verified artefacts** when you can.', '**Secrets scanning** on PRs — stop leaks early.'],
        'example': '### Lab: pipeline security checklist\n\n- [ ] `npm audit` / equivalent in CI (or Dependabot)\n- [ ] Secret scan on PR\n- [ ] Container scan on image build\n- [ ] Deploy role can only push to intended environment\n- [ ] No long-lived access keys in developer laptops for prod\n\nDocument where production secrets live (vault / cloud secret manager).\n',
        'practice': ['Enable a dependency update bot or weekly audit note.', 'List every credential your pipeline needs and why.', 'Practise rotating one non-prod secret end-to-end.'],
        'mistakes': ['Admin credentials in CI “for convenience”', 'Ignoring critical CVEs in base images', 'Sharing one cloud key across all environments'],
        'stretch': 'Add an OIDC-style cloud login from CI instead of static keys (where supported).',
        'quiz': [
            ('Least privilege for deploy credentials means…', ['CI can do anything in the cloud account', 'CI can only perform required deploy actions', 'Developers email passwords around', 'Secrets live in the frontend bundle'], 1),
            ('Dependency scanning helps you…', ['Know vulnerable libraries you ship', 'Skip tests', 'Avoid version control', 'Disable TLS'], 0),
            ('Secret scanning on PRs is valuable because…', ['It catches accidental key commits early', 'It replaces IAM', 'It makes builds slower for fun', 'It encrypts the database automatically'], 0),
            ('Why separate prod and non-prod credentials?', ['To limit blast radius of leaks', 'To confuse newcomers', 'Clouds require identical keys', 'So rollbacks are impossible'], 0),
            ('Rotating a secret means…', ['Issuing a new value and retiring the old one safely', 'Printing it in Slack', 'Never changing it', 'Storing it in the README'], 0),
        ],
    },
    'devops/10-capstone-delivery': {
        'goals': ['Ship a small service with CI, container, and a release note', 'Demonstrate rollback and a basic dashboard/alert idea', 'Present your path as a portfolio story'],
        'why': 'Capstones prove you can connect habits end-to-end — the skill employers and teams actually need.',
        'ideas': ['**Thin vertical slice** — one endpoint, real pipeline, real notes.', '**Evidence pack** — repo link, pipeline screenshot, runbook, metrics note.', '**Honest limits** — say what you did not automate yet.'],
        'example': '### Capstone definition of done\n\n- [ ] Repo with README + `.env.example`\n- [ ] CI runs tests on PR\n- [ ] Docker image builds with a version tag\n- [ ] Compose or cloud deploy path documented\n- [ ] Release checklist + rollback\n- [ ] One structured log or metric + one alert idea\n- [ ] 5-minute demo script\n',
        'practice': ['Complete the definition of done for your sample service.', 'Record a 5-minute walkthrough (or written script).', 'List three improvements for a “v2” backlog.'],
        'mistakes': ['Over-scoping (microservices mesh on day one)', 'No evidence artefacts — only claims', 'Skipping rollback practice'],
        'stretch': 'Add a canary or feature flag to the demo story.',
        'quiz': [
            ('A strong DevOps capstone emphasises…', ['End-to-end delivery evidence, not tool name-dropping', 'Only a fancy logo', 'No documentation', 'Production secrets in the demo video'], 0),
            ('Why include a rollback in the capstone?', ['It shows operational maturity', 'It is optional trivia', 'It replaces testing', 'It proves you never deploy'], 0),
            ('Thin vertical slice means…', ['One small path done well across build→run→observe', 'Every cloud product enabled', 'No CI', 'Only slides, no code'], 0),
            ('Your evidence pack should include…', ['Pipeline proof and a runbook', 'Only vibes', 'Customer passwords', 'Unrelated homework from another class'], 0),
            ('Calling out limits in your write-up is…', ['Professional and builds trust', 'A failure', 'Forbidden', 'A reason to hide the repo'], 0),
        ],
    },
    'aws/01-aws-foundations': {
        'goals': ['Navigate regions, AZs, and the shared responsibility model', 'Create a learning account habit (billing alarm first)', 'Use AWS CLI or Console with an IAM user/role — not root daily'],
        'why': 'AWS is huge. Foundations prevent surprise bills and root-key disasters before you touch fancy services.',
        'ideas': ['**Account = blast radius boundary** — prefer separate learning/prod later.', '**Region choice** — latency, data residency, service availability.', '**Shared responsibility** — AWS secures the cloud; you secure *in* the cloud.', '**Billing alarm day one** — CloudWatch billing or Budgets.'],
        'example': '### Lab: account hygiene\n\n1. Enable MFA on root; create an admin IAM user/role for daily work.\n2. Create a Budget alert (e.g. $10).\n3. `aws sts get-caller-identity` and screenshot (redact account specifics if sharing).\n\n```bash\naws sts get-caller-identity\naws configure list\n```\n',
        'practice': ['Set a billing alert.', 'Document your home region and why.', 'Write the shared responsibility split for EC2 vs Lambda in one paragraph.'],
        'mistakes': ['Using root access keys daily', 'No billing alarm', 'Leaving unused resources running'],
        'stretch': 'Enable Cost Explorer and identify the top cost category after a tiny lab.',
        'quiz': [
            ('Shared responsibility means…', ['AWS handles everything including your IAM policies always', 'AWS secures the cloud; you secure your configs, data, and access', 'Customers never patch anything ever', 'Billing is optional'], 1),
            ('Why set a budget alarm early?', ['To catch surprise spend', 'To slow the console', 'AWS requires it to log in', 'It replaces IAM'], 0),
            ('Daily work should use…', ['Root user always', 'IAM users/roles with MFA where appropriate', 'Public anonymous access', 'Shared Facebook login'], 1),
            ('A region is…', ['A geographic area with multiple Availability Zones', 'A single rack under your desk', 'Only a billing fiction', 'A Kubernetes pod'], 0),
            ('`aws sts get-caller-identity` helps you…', ['Confirm which principal you are acting as', 'Delete VPCs', 'Compile Java', 'Disable MFA'], 0),
        ],
    },
    'aws/02-iam-and-security': {
        'goals': ['Explain users, groups, roles, and policies', 'Write a least-privilege policy sketch for S3 read-only', 'Prefer roles over long-lived access keys'],
        'why': 'IAM mistakes are the #1 cloud self-own. Least privilege and roles beat shared access keys.',
        'ideas': ['**Identity vs permissions** — who you are vs what you can do.', '**Roles for compute** — EC2/Lambda assume roles; avoid embedding keys.', '**Deny by default** — grant only needed actions/resources.', '**CloudTrail** — know who changed what.'],
        'example': '### Lab: read-only S3 policy sketch\n\n```json\n{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Effect": "Allow",\n    "Action": ["s3:GetObject", "s3:ListBucket"],\n    "Resource": [\n      "arn:aws:s3:::my-learning-bucket",\n      "arn:aws:s3:::my-learning-bucket/*"\n    ]\n  }]\n}\n```\n\nAttach to a role used by your learning EC2/CloudShell — not AdministratorAccess for everything.\n',
        'practice': ['Create a least-privilege policy for one task.', 'List three actions that should never be `*` in learning accounts casually.', 'Enable CloudTrail (or confirm it) and find one event.'],
        'mistakes': ['`AdministratorAccess` on every principal', 'Access keys in GitHub', 'Public S3 ACLs “temporarily” forgotten'],
        'stretch': 'Use IAM Access Analyzer findings on one resource.',
        'quiz': [
            ('An IAM role is useful because…', ['Compute can assume temporary credentials', 'It replaces VPCs', 'It stores objects like S3', 'It is a database engine'], 0),
            ('Least privilege means…', ['Grant only needed actions on needed resources', 'Always use AdministratorAccess', 'Share root keys', 'Disable MFA'], 0),
            ('Long-lived access keys in git are…', ['A serious incident waiting to happen', 'Best practice', 'Required by AWS', 'Safer than roles'], 0),
            ('CloudTrail helps you…', ['Audit API activity', 'Resize disks automatically', 'Compile containers', 'Buy domains'], 0),
            ('Prefer roles over embedded keys because…', ['Credentials can be temporary and rotatable by design', 'Roles never need policies', 'Keys are illegal', 'IAM is optional'], 0),
        ],
    },
    'aws/03-vpc-networking': {
        'goals': ['Draw public vs private subnets', 'Explain route tables, IGW, and NAT at a high level', 'Place a web tier and data tier thoughtfully'],
        'why': 'Networking mistakes expose databases or block deploys. A simple VPC sketch prevents both.',
        'ideas': ['**Public subnet** — route to Internet Gateway for inbound public services.', '**Private subnet** — no public IP; egress via NAT if needed.', '**Security groups** — stateful allow-lists on ENIs.', '**NACLs** — optional extra subnet-level filter (keep simple at first).'],
        'example': '### Lab: napkin VPC\n\n```text\nVPC 10.0.0.0/16\n  public-a  10.0.0.0/24  → IGW\n  private-a 10.0.10.0/24 → NAT (egress)\nSG-web: allow 443 from 0.0.0.0/0\nSG-db:  allow 5432 from SG-web only\n```\n\nNever put the database in a public subnet for learning “convenience”.\n',
        'practice': ['Draw your VPC with two subnets and two security groups.', 'Write which resources get public IPs and why.', 'Trace a packet from browser → ALB/instance → DB.'],
        'mistakes': ['0.0.0.0/0 to SSH on 22 permanently', 'Database in public subnet', 'Overlapping CIDRs when peering later'],
        'stretch': 'Add a second AZ subnet pair for high availability sketch.',
        'quiz': [
            ('A private subnet typically…', ['Has no direct IGW route for instances', 'Must be publicly reachable', 'Cannot have any routes', 'Replaces IAM'], 0),
            ('Security groups are…', ['Stateful firewalls attached to ENIs', 'S3 bucket policies', 'DNS records', 'Billing tags only'], 0),
            ('NAT gateways help private instances…', ['Reach the internet for egress without being publicly addressed', 'Accept inbound internet traffic by default', 'Replace TLS', 'Store objects'], 0),
            ('Allowing DB ports only from the app SG is an example of…', ['Least privilege networking', 'Public by default', 'Disabling encryption', 'Cross-region replication'], 0),
            ('Why sketch two AZs?', ['Resilience if one AZ fails', 'AWS bills less automatically', 'IAM becomes optional', 'You can skip backups'], 0),
        ],
    },
    'aws/04-ec2-and-compute': {
        'goals': ['Launch a tiny EC2 (or use CloudShell) safely', 'Choose instance sizing with cost in mind', 'Connect via SSM Session Manager mindset (prefer over open SSH)'],
        'why': 'EC2 is the classic compute primitive. Learning it teaches AMIs, disks, and networking that other services abstract.',
        'ideas': ['**AMI + instance type + storage + SG** — the four knobs.', '**Stop vs terminate** — cost and data implications.', '**User data** — bootstrap carefully; prefer images/CI later.', '**SSM over bastion** when possible.'],
        'example': "### Lab: free-tier minded instance\n\n1. Amazon Linux in your home region, t2/t3.micro if eligible.\n2. SG: no 22 from the world; prefer SSM role + `AmazonSSMManagedInstanceCore`.\n3. Tag `Project=learning`, `KeepUntil=YYYY-MM-DD`.\n4. Stop or terminate when done; verify billing.\n\n```bash\n# from CloudShell / your laptop with rights:\naws ec2 describe-instances --query 'Reservations[].Instances[].InstanceId'\n```\n",
        'practice': ['Launch, tag, connect (SSM or tightly scoped SSH), install nothing unnecessary, stop.', 'Write when you’d pick EC2 vs Lambda vs containers.', 'Document disk: root volume size and whether data must persist.'],
        'mistakes': ['Forgetting to stop instances', 'Wide-open SSH', 'Storing unique data only on ephemeral instance store without backup'],
        'stretch': 'Create a simple launch template or note why you’d want one.',
        'quiz': [
            ('Stopping an EC2 instance…', ['Usually stops compute charges (EBS may still cost)', 'Deletes the VPC', 'Removes IAM', 'Is identical to terminating always'], 0),
            ('Why prefer SSM Session Manager?', ['Avoid opening SSH to the world', 'It replaces all security groups', 'It is a database', 'It disables CloudTrail'], 0),
            ('Tags help with…', ['Cost allocation and ownership', 'Faster CPUs magically', 'Skipping patches', 'Public access'], 0),
            ('User data scripts should…', ['Be treated carefully — prefer immutable images for prod', 'Contain production secrets always', 'Never be reviewed', 'Replace IAM policies'], 0),
            ('Pick EC2 when you need…', ['Full OS control / long-running custom runtimes', 'Only a single SQL query forever', 'DNS only', 'Object storage only'], 0),
        ],
    },
    'aws/05-s3-and-storage': {
        'goals': ['Create a private bucket with Block Public Access on', 'Explain versioning and lifecycle basics', 'Generate a pre-signed URL mindset for temporary access'],
        'why': 'S3 is everywhere — backups, static assets, data lakes. Public bucket mistakes make headlines.',
        'ideas': ['**Private by default** — Block Public Access.', '**Versioning** — recover from overwrite/delete.', '**Lifecycle** — transition/expire to control cost.', '**Encryption** — SSE-S3/SSE-KMS; know which you chose.'],
        'example': '### Lab: private bucket + versioning\n\n```bash\naws s3 mb s3://YOUR-UNIQUE-LEARNING-BUCKET\naws s3api put-public-access-block --bucket YOUR-UNIQUE-LEARNING-BUCKET \\\n  --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true\naws s3api put-bucket-versioning --bucket YOUR-UNIQUE-LEARNING-BUCKET \\\n  --versioning-configuration Status=Enabled\necho "hello" > note.txt\naws s3 cp note.txt s3://YOUR-UNIQUE-LEARNING-BUCKET/\n```\n',
        'practice': ['Create a private versioned bucket and upload a file.', 'Write a lifecycle rule idea (e.g. expire incomplete uploads).', 'Explain when static website hosting is OK vs CloudFront+OAC patterns.'],
        'mistakes': ['Public ACLs for “just a second”', 'No versioning on important backups', 'Leaving old incomplete multipart uploads forever'],
        'stretch': 'Enable access logging or server access logs to another bucket.',
        'quiz': [
            ('Block Public Access should be…', ['On unless you have a deliberate public design', 'Always off', 'Irrelevant', 'Only for EC2'], 0),
            ('Versioning helps you…', ['Recover from accidental deletes/overwrites', 'Speed up CPUs', 'Replace IAM', 'Disable encryption'], 0),
            ('Lifecycle policies help…', ['Control cost by transitioning/expiring objects', 'Create VPCs', 'Compile code', 'Issue certificates'], 0),
            ('Pre-signed URLs are for…', ['Temporary authorised access without making the object public', 'Permanent anonymous world access', 'Deleting accounts', 'Replacing HTTPS'], 0),
            ('S3 is primarily…', ['Object storage', 'A relational database', 'A VPC router', 'An IAM identity'], 0),
        ],
    },
    'aws/06-rds-and-data': {
        'goals': ['Explain why managed databases exist', 'Place RDS in private subnets', 'Plan backups, multi-AZ idea, and credential storage'],
        'why': 'Data loss ends careers. Managed DBs trade some control for backups, patching, and HA options.',
        'ideas': ['**Private placement** — no public accessibility for learning defaults.', '**Automated backups + snapshots** — know RPO/RTO in plain words.', '**Multi-AZ** — standby for failover (cost vs risk).', '**Credentials in Secrets Manager** — not in app code.'],
        'example': '### Lab: design note (even if you do not provision paid RDS)\n\nWrite a one-pager:\n\n- Engine: Postgres\n- Subnets: private\n- PubliclyAccessible: false\n- Backup retention: 7 days\n- App connects via SG from app tier only\n- Password: Secrets Manager rotation sketch\n',
        'practice': ['Complete the design note.', 'Compare RDS vs self-managed Postgres on EC2 for your use case.', 'Define RPO/RTO targets in one sentence each.'],
        'mistakes': ['Publicly accessible database', 'Single snapshot never tested', 'Huge instance “just in case” without measuring'],
        'stretch': 'Sketch read replica use for reporting workloads.',
        'quiz': [
            ('RDS public accessibility for a typical app DB should be…', ['false — keep it private', 'true always', 'irrelevant', 'controlled only by S3'], 0),
            ('Automated backups help you meet…', ['Recovery Point Objectives', 'Font guidelines', 'DNS TTLs', 'IAM password length only'], 0),
            ('Multi-AZ primarily improves…', ['Availability within a region', 'Cross-continent latency always', 'S3 object listing speed', 'Git merge quality'], 0),
            ('Store DB passwords in…', ['A secrets manager / parameter store pattern', 'The mobile app UI strings', 'Public GitHub', 'Security group names'], 0),
            ('App → DB traffic should be limited by…', ['Security groups (and private networking)', 'Making the DB public', 'Disabling TLS always', 'Using root AWS keys in SQL'], 0),
        ],
    },
    'aws/07-lambda-serverless': {
        'goals': ['Describe event-driven Lambda use cases', 'Package a tiny function and think about IAM role', 'Watch cold starts, timeouts, and cost dimensions'],
        'why': 'Serverless removes server babysitting for spiky or event workloads — if you design events and IAM well.',
        'ideas': ['**Function + trigger + role** — the core trio.', '**Stateless** — put state in DB/S3.', '**Timeouts & memory** — affect CPU and cost.', '**Least privilege role** — only needed AWS actions.'],
        'example': '### Lab: hello function mindset\n\n```python\ndef handler(event, context):\n    return {"statusCode": 200, "body": "ok"}\n```\n\nTriggers to know: API Gateway/Function URL, S3 event, SQS.\nIAM: permission to write logs to CloudWatch; nothing else until needed.\n',
        'practice': ['Deploy or sketch a hello function with logs.', 'List three good and three bad Lambda use cases.', 'Set timeout intentionally (not max by default).'],
        'mistakes': ['VPC-attached Lambda without understanding ENI cold starts (when applicable)', 'Huge deployment packages', 'Admin role on the function'],
        'stretch': 'Add an S3 trigger that processes an uploaded object key (name only).',
        'quiz': [
            ('Lambda functions should be…', ['Mostly stateless; externalise state', 'Long-lived SSH servers', 'Replacements for all databases', 'Run without any IAM role'], 0),
            ('A common Lambda trigger is…', ['Object uploaded to S3 / HTTP via API Gateway', 'Physical doorbell only', 'Git merge without AWS', 'Changing DNS TTL by hand'], 0),
            ('Memory setting on Lambda also influences…', ['Allocated CPU and cost characteristics', 'Your git username', 'VPC CIDR', 'S3 consistency model'], 0),
            ('CloudWatch Logs for Lambda are useful to…', ['Debug failures and understand invocations', 'Host static websites', 'Issue SSL certs', 'Create subnets'], 0),
            ('Least privilege on a function role means…', ['Only actions the function needs', 'AdministratorAccess always', 'No logging', 'Public anonymous invoke for everything'], 0),
        ],
    },
    'aws/08-monitoring-cloudwatch': {
        'goals': ['Find default metrics for a service you used', 'Create an alarm idea with a threshold', 'Use logs insights mindset for one query'],
        'why': 'Without CloudWatch (or equivalent), you learn about outages from Twitter.',
        'ideas': ['**Metrics → Alarms → Actions** (SNS/email).', '**Dashboards** for a service overview.', '**Logs retention** — cost vs need.', '**Alarms on symptoms** tied to user impact.'],
        'example': '### Lab: alarm sketch\n\nMetric: `5XXError` on ALB or `Errors` on Lambda  \nThreshold: > 1% of requests for 5 minutes  \nAction: email SNS topic  \n\nWrite the plain-English symptom: “Users cannot complete checkout.”\n',
        'practice': ['Create or sketch one alarm + SNS email.', 'Set log retention intentionally on a log group.', 'Write one Logs Insights style question you care about.'],
        'mistakes': ['No alarms at all', 'Alarm on noisy metrics with no runbook', 'Infinite log retention on debug noise'],
        'stretch': 'Composite alarm or anomaly detection note.',
        'quiz': [
            ('CloudWatch alarms should usually map to…', ['User-visible symptoms', 'Random debug prints', 'Laptop fan speed', 'Number of README emojis'], 0),
            ('SNS is often used to…', ['Notify humans/systems when an alarm fires', 'Replace VPCs', 'Build Docker images', 'Issue IAM users'], 0),
            ('Log retention settings matter because…', ['Storage costs and compliance needs', 'They change instance types', 'They disable HTTPS', 'They create subnets'], 0),
            ('A dashboard helps during incidents by…', ['Showing key golden signals quickly', 'Automatically fixing code', 'Replacing runbooks entirely', 'Granting AdministratorAccess'], 0),
            ('If an alarm has no runbook…', ['On-call may not know what to do — write one', 'That is ideal', 'AWS will page customers for you', 'You should delete CloudTrail'], 0),
        ],
    },
    'aws/09-cost-and-well-architected': {
        'goals': ['Use tags and Cost Explorer categories', 'Name the Well-Architected pillars at a high level', 'Apply one cost-saving action (stop/rightsize/lifecycle)'],
        'why': 'Cloud cost is an architecture problem. Well-Architected gives a vocabulary for trade-offs.',
        'ideas': ['**Cost visibility** before optimisation.', '**Rightsizing & scheduling** — stop learning boxes overnight.', '**Pillars** — operational excellence, security, reliability, performance, cost, sustainability.', '**Questions over dogma** — WA is a review lens.'],
        'example': '### Lab: $0-ish cleanup hunt\n\n1. Open Cost Explorer (or billing).\n2. List running resources with tags.\n3. Stop/terminate abandoned labs.\n4. Write one Well-Architected question you would ask your design (e.g. “How do we recover from AZ loss?”).\n',
        'practice': ['Tag all lab resources consistently.', 'Perform one cleanup that reduces idle cost.', 'Answer two WA questions for your sample app in writing.'],
        'mistakes': ['Optimising before measuring', 'Orphaned Elastic IPs / idle NAT / forgotten disks', 'Treating WA as paperwork only'],
        'stretch': 'Set a weekly calendar reminder for lab cleanup.',
        'quiz': [
            ('Cost Explorer helps you…', ['See where money goes', 'Compile Kotlin', 'Create IAM users automatically', 'Disable MFA'], 0),
            ('Rightsizing means…', ['Matching resource size to actual need', 'Always picking the largest instance', 'Deleting all monitoring', 'Using root keys'], 0),
            ('Well-Architected is primarily…', ['A set of pillars/questions for reviewing designs', 'A mandatory paid product SKU only', 'A replacement for IAM', 'A DNS standard'], 0),
            ('Idle NAT gateways and forgotten EBS volumes…', ['Can quietly burn money', 'Are always free', 'Improve security automatically', 'Replace backups'], 0),
            ('Tags support cost work by…', ['Allocating spend to projects/teams', 'Speeding CPUs', 'Encrypting S3 alone', 'Creating AZs'], 0),
        ],
    },
    'aws/10-capstone-aws-app': {
        'goals': ['Deploy a tiny architecture: compute + storage + IAM + monitoring note', 'Prove private data placement and a billing alarm', 'Package diagrams + commands as portfolio evidence'],
        'why': 'Connecting IAM, network, compute, and storage is the real AWS skill — not memorising product logos.',
        'ideas': ['**Minimal viable cloud app** — static site on S3+CloudFront *or* API on managed compute.', '**Diagram first** — boxes and trust boundaries.', '**Cleanup script/notes** — leave no orphan spend.'],
        'example': '### Capstone options (pick one)\n\n**A.** Private S3 assets + CloudFront (or private bucket + pre-signed demo)  \n**B.** Container/EC2/App behind SG + S3 for uploads + CloudWatch alarm  \n**C.** Lambda + API Gateway + DynamoDB/S3 learning slice\n\nDefinition of done: diagram, IAM notes, deploy steps, alarm, cleanup steps.\n',
        'practice': ['Complete one option end-to-end at learning scale.', 'Record cleanup commands/checklist.', 'Write a 5-minute demo script.'],
        'mistakes': ['Public databases', 'No cleanup — surprise bill', 'Admin IAM everywhere'],
        'stretch': 'Add HTTPS and a custom domain note (even if deferred).',
        'quiz': [
            ('An AWS capstone should prove…', ['You can connect identity, network, compute, data, and monitoring', 'You memorised every SKU', 'You used root keys in the demo', 'You skipped diagrams'], 0),
            ('Why include cleanup steps?', ['Learning accounts rack up idle cost otherwise', 'AWS deletes everything nightly always', 'Cleanup is optional trivia', 'It disables CloudTrail'], 0),
            ('A simple architecture diagram helps…', ['Reviewers see trust boundaries', 'CPUs run faster', 'IAM become unnecessary', 'Buckets become public safely'], 0),
            ('Least privilege in the capstone means…', ['Roles/policies match the app’s needs', 'AdministratorAccess on every role', 'No logging', 'Public SSH everywhere'], 0),
            ('Billing alarms belong in the capstone because…', ['Cost feedback is part of operating on cloud', 'They replace security groups', 'They compile code', 'They are purely cosmetic'], 0),
        ],
    },
}

from premium_module_content_part2 import MODULES as _PART2

MODULES.update(_PART2)
